#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
##### export PATH=$HOME/.local/share/go/bin:$PATH
##### export GOPATH=$HOME/.local/share/go
##### export PATH=$HOME/.fnm:$PATH
##### export PATH="$PATH:./node_modules/.bin"
##### eval "$(fnm env)"
# eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"

# NPM packages in homedir
NPM_PACKAGES="$HOME/.npm-packages"

# Tell our environment about user-installed node tools
PATH="$NPM_PACKAGES/bin:$PATH"
# Unset manpath so we can inherit from /etc/manpath via the `manpath` command
## unset MANPATH  # delete if you already modified MANPATH elsewhere in your configuration
## MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

# Tell Node about these packages
NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"

##### # >>> conda initialize >>>
##### # !! Contents within this block are managed by 'conda init' !!
##### __conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
##### if [ $? -eq 0 ]; then
#####     eval "$__conda_setup"
##### else
#####     if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
#####         . "$HOME/.miniconda/etc/profile.d/conda.sh"
#####     else
#####         export PATH="$HOME/.miniconda/bin:$PATH"
#####     fi
##### fi
##### unset __conda_setup
##### # <<< conda initialize <<<

